# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pomo}
  s.version = "0.5.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Grosser"]
  s.date = %q{2009-11-18}
  s.email = %q{grosser.michael@gmail.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "README.markdown",
     "Rakefile",
     "VERSION.yml",
     "lib/pomo.rb",
     "lib/pomo/mo_file.rb",
     "lib/pomo/po_file.rb",
     "lib/pomo/translation.rb",
     "pomo.gemspec",
     "prototype_treetop/po.treetop",
     "prototype_treetop/test.rb",
     "spec/files/complex.mo",
     "spec/files/empty.mo",
     "spec/files/plural.mo",
     "spec/files/singular.mo",
     "spec/files/singular_2.mo",
     "spec/pomo/mo_file_spec.rb",
     "spec/pomo/po_file_spec.rb",
     "spec/pomo/translation_spec.rb",
     "spec/spec_helper.rb",
     "vendor/README.rdoc",
     "vendor/iconv.rb",
     "vendor/mofile.rb"
  ]
  s.homepage = %q{http://github.com/grosser/pomo}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Ruby/Gettext: A .po and .mo file parser/generator}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/pomo/translation_spec.rb",
     "spec/pomo/mo_file_spec.rb",
     "spec/pomo/po_file_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

